clear; close all;

p  = 2;   % polynomial degree. May be needed in Problem.Time_Step
Re = 400; % Reynolds number.   May be needed in Problem.Time_Step

Problem = struct(...
'Title'             ,  'Cavity',   ...
'Subtitle'          ,  'twirl',    ...
'Identifier'        ,  'a',        ...
'Geometry'          ,  'Identity', ...
'Geometry_param'    ,  1,          ...
'Polynomial_Degree' ,  [p,p],      ...
'H_Max'             ,  1/8,       ...
'H_Min'             ,  1/12,       ...
'Reynolds'          ,  Re,         ...
'Newton_TOL'        ,  1e-10,      ...
'Newton_Max_It'     ,  12,         ...
'Time_Step'         ,  @(h) min(h^((p+1)/2), h^2 /4*Re), ...
'Time_Range'        ,  [0,5]);

main_init;
main_assemble;
main_time_loop;
main_dump_results;

